# TODO:
# * proper deploy (with dependencies, etc.)
# * sanitizers
# * Coverity
# # Valgrind

name: CI
on:
  push:
    paths-ignore:
    - 'LICENSE.txt'
    - 'README.md'
    - '.gitignore'
  pull_request:
    paths-ignore:
    - 'LICENSE.txt'
    - 'README.md'
    - '.gitignore'
jobs:
  Baseline:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-latest]
        cc: [gcc, clang]
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: scripts/travis.sh
  Coverage:
    needs: Baseline
    runs-on: ubuntu-latest
    environment: secrets
    env:
      COVERAGE: 1
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Run tests and upload coverage
      run: scripts/travis.sh
